force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Produto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto__c/fields/QTD__c.field-meta.xml
<CustomField>
    <fullName>QTD__c</fullName>
    <label>QTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProdutosService.cls
public with sharing class ProdutosService {
    public static void updateQtdProduto(Map<Id, Decimal> idQtdMap) {
        List<Produto__c> produtosToUpdate = new List<Produto__c>();
        try {
            List<Produto__c> produtos = ProdutosRepository.getInstance().selectById(idQtdMap.keySet());
            for (Produto__c prod : produtos) {
                Produto__c produto = new Produto__c(Id = prod.Id, QTD__c = prod.QTD__c - idQtdMap.get(prod.Id));
                produtosToUpdate.add(produto);
            }
            Database.update(produtosToUpdate);
        } catch (Exception ex) {
            System.debug('Message: ' + ex.getMessage());
            System.debug('Stack: ' + ex.getStackTraceString());
        }
    }
}